name: firebase_invites
description: A new Flutter plugin.
version: 0.2.0
author:
homepage:

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.2.2

flutter:
  plugin:
    androidPackage: io.flutter.plugins.firebaseinvites
    pluginClass: FirebaseInvitesPlugin

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.2.4 <2.0.0"
